Readme file updated
henkaku-center/henkaku-nengajo-frontend pull request #114
Opened 2022-12-31 13:36 UTC by maddy020

Readme file has been updated

2023-01-01 02:26 UTC, alecrem commented
I'm very sorry but this repo is not too easy to collaborate on if you are not a member of our community. Instructions are often unclear like this, and it would take us a shorter time to change the README ourselves than it would take us letting you know everything that needs to be changed and how, so please do not take it personally if we sometimes cannot follow up with your activity.

I see that you are students trying to collaborate on open source projects, and I think that is great and would like to encourage you! I'm just sorry that we are a rather closed community and documentation is not too good.

2023-01-01 02:29 UTC, alecrem requested changes

2023-01-01 02:29 UTC, alecrem commented on README.md
> +# or
Notice that we don't have a `package-lock.json` but just a `yarn.lock`. We don't use npm — only yarn.

So please include only instructions for yarn.

2023-01-01 02:29 UTC, alecrem commented on README.md
>  npm run dev
It would be nice if you could also remove the npm instructions that were present on the original README.

2023-01-01 12:38 UTC, maddy020 commented
> I'm very sorry but this repo is not too easy to collaborate on if you are not a member of our community. Instructions are often unclear like this, and it would take us a shorter time to change the README ourselves than it would take us letting you know everything that needs to be changed and how, so please do not take it personally if we sometimes cannot follow up with your activity.
> 
> I see that you are students trying to collaborate on open source projects, and I think that is great and would like to encourage you! I'm just sorry that we are a rather closed community and documentation is not too good.

Ok no issue

2023-01-02 07:30 UTC, alecrem approved these changes
Thank you! LGTM.

2023-01-02 07:31 UTC, merged